name: Update SAR source

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Manual
        run: |
          mkdir -p gcp/roles/
          gcloud iam roles list --show-deleted --format json | jq -r '.[]|[.name,(.name | split("/")[-1])] | @tsv' |
          while IFS=$'\t' read -r name shortname; do
              echo "Writing $shortname.json"
              gcloud iam roles describe "$name" --format json > gcp/roles/$shortname.json || echo "Failure to write $shortname.json"
          done
          az provider operation list > azure-provider-operations.json
          az role definition list --query '[?roleType == `BuiltInRole`].{assignableScopes: assignableScopes, description: description, permissions: permissions, roleName: roleName, roleType: roleType, type: type}' > azure-built-in-roles.json
          curl https://raw.githubusercontent.com/duo-labs/parliament/main/utils/update_iam_data.py -o update_iam_data.py
          pip3 install bs4 requests
          python3 update_iam_data.py > js/iam_definition.json
          sleep 1
          python3 patch_iam_definition.py
          sleep 1
          rm -rf docs/ update_iam_data.py
          # sudo apt -y install git nodejs
          git clone https://github.com/z0ph/MAMIP.git
          python3 add_managed_policies.py
          npm i
          npm update aws-sdk
          node add_docs.js
          python3 update_counts.py
      - name: Commit files
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          set -eux
          git config --local user.email "githubbot@ian.mn"
          git config --local user.name "Ian Mckay [bot]"
          git add .
          git commit -m "Update SAR data" -a || exit 0
          remote_repo="https://iann0036-bot:${BOT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:main
