name: Update SAR source

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Manual
        run: |
          curl https://raw.githubusercontent.com/duo-labs/parliament/main/utils/update_iam_data.py -o update_iam_data.py
          pip3 install bs4
          python3 update_iam_data.py > js/iam_definition.json
          sleep 1
          python3 patch_iam_definition.py
          sleep 1
          rm -rf docs/ update_iam_data.py
          sudo apt -y install git nodejs
          git clone https://github.com/z0ph/MAMIP.git
          python3 add_managed_policies.py
          npm i
          npm update aws-sdk
          node add_docs.js
          python3 update_counts.py
      - name: Commit files
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          set -eux
          git config --local user.email "githubbot@ian.mn"
          git config --local user.name "Ian Mckay [bot]"
          git add .
          git commit -m "Update SAR data" -a || exit 0
          remote_repo="https://iann0036-bot:${BOT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:main
